FROM quay.io/keycloak/keycloak:24.0.0

ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=true
ENV KC_HTTP_ENABLED=true
ENV PROXY_ADDRESS_FORWARDING=true

CMD ["start", "--proxy=edge", "--log-level=INFO"]
