ARG KEYCLOAK_VERSION=21.0.1

FROM docker.io/library/keycloak-builder as mvn_builder

FROM quay.io/keycloak/keycloak:${KEYCLOAK_VERSION} as builder
COPY --from=mvn_builder /tmp/target/*.jar /opt/keycloak/providers/
COPY --from=mvn_builder /tmp/target/*.jar /opt/keycloak/deployments/

COPY idps/wechat-mobile/keycloak-services-social-weixin.jar \
    /opt/keycloak/providers/

COPY idps/wecom/keycloak-services-social-wechat-work.jar \
    /opt/keycloak/providers/
COPY idps/wecom/templates/realm-identity-provider-wechat-work.html \
    /opt/keycloak/themes/base/admin/resources/partials
COPY idps/wecom/templates/realm-identity-provider-wechat-work-ext.html \
    /opt/keycloak/themes/base/admin/resources/partials

#COPY  temp/* /opt/keycloak/themes/base/admin/resources/partials
#COPY  ui/font_iconfont /opt/keycloak/themes/keycloak/common/resources/lib/font_iconfont
#COPY  ui/theme.properties /opt/keycloak/themes/keycloak/login/

COPY idps/phone/keycloak-phone-provider.jar /opt/keycloak/providers/
COPY idps/phone/keycloak-phone-provider.resources.jar /opt/keycloak/providers/
COPY idps/phone/keycloak-sms-provider-aliyun.jar /opt/keycloak/providers/


ENV KC_HOSTNAME_STRICT=false
ENV KC_HOSTNAME_STRICT_HTTPS=false
ENV KC_HTTP_ENABLED=true

USER 1000

RUN /opt/keycloak/bin/kc.sh build --health-enabled=true

FROM quay.io/keycloak/keycloak:$KEYCLOAK_VERSION
COPY --from=builder /opt/keycloak/ /opt/keycloak/
WORKDIR /opt/keycloak

# https://www.keycloak.org/server/logging
ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start-dev", "--spi-phone-default-service=aliyun", "--spi-message-sender-service-aliyun-region=cn-hangzhou", "--spi-message-sender-service-aliyun-key=*", "--spi-message-sender-service-aliyun-secret=*", "--spi-message-sender-service-aliyun-auth-template=*", "--hostname-strict=false", "--features=\"preview,scripts\"", "--log-level=INFO"]

